### ISSUE TITLE
Shorten the funnel

### ISSUE THREAD

**Issue by foxbunny** [Outernet-Project/broadcast-portal#15]
Change the progress through the uplink wizard by implementing the following:
- The [content form](http://localhost:8080/broadcast/content/) should be the intial page, and the blurb at the top should be above the form.
- The step 2 of the wizard should be merged with the first step and the form should have the following fields (required items marked with a !, items that are TBD are marked with ?):
  - file !
  - title !
  - language
  - license ?
  - source URL
  - email
- Keep both submit buttons (paid & free, but removal of paid option is TBD).

**Comment by syedkarim** [comment]
In the future, a paid button will be used to email us to review the content immediately. 
"For $1 we will review the content within 24 hours". The button leads to payment processing and an email to various reviewers.
